### ISSUE TITLE
NPE on getSkinName when the server is behind BungeeCord

### ISSUE THREAD

**Issue by HSGamer** [SkinsRestorer/SkinsRestorerX#984] opened 2022-06-22 10:32 UTC
## Describe the bug

I got an NPE when using `SkinsRestorerAPI#getSkinName` on my Spigot server that has `bungeecord` enabled

## How can we reproduce what you got?

1. Setup BungeeCord, then add a Spigot server to the proxy
2. Install SkinsRestorer for both BungeeCord & Spigot
3. Make a plugin that call `SkinsRestorerAPI#getSkinName`
4. Try the plugin and get the error

**Expected behavior**

No Exception

**Screenshots**
No screenshot, just the log

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**

* SkinsRestorer: 14.2.0
* Spigot version: 1.17.1
* Bungeecord version: 1.19
* IF bungee, did you put the plugin on all servers: Yes
* Java: 8
* plugin list bungee & spigot: SkinsRestorer, FillSkinsRestorerProfile (my plugin)
* MinecraftLauncher?: MultiMC
* if multiverse, (censored) worlds file:

## Logs

Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs
from **Bungeecord *AND* Spigot/Bukkit**)
https://hastebin.app/62b2ee9dd5c6ab001c626949

**Comment by xknat** [comment] 2022-06-22 10:35
api should be done on bungee side, this is where the data is stored

**Comment by HSGamer** [comment] 2022-06-22 11:32
Well... I'm making a plugin on Paper that fix the slow fetching on `PlayerProfile` by forcing it with SkinsRestorer's data. It HAS to be on Paper side.
It worked with no exception on older version of `SkinsRestorer`
Is there any alternative way to do that?

**Comment by HSGamer** [comment] 2022-06-22 11:38
I'll find it myself.

**Comment by xknat** [comment] 2022-07-20 18:00
Duplicate of https://github.com/SkinsRestorer/SkinsRestorerX/issues/1006

**Closed as completed by xknat** 2022-07-20 18:00 UTC
