### ISSUE TITLE
Tracer Bug - Causing permanent tracers to every player joining (easy raiding)

### ISSUE THREAD

**Issue by Kongolan** [SkinsRestorer/SkinsRestorerX#237] opened 2020-04-29 13:23 UTC
There is a crucial bug and i finally narrowed down it's caused by SkinsRestorer. It seems like updating the whole server on skin setting gives you a permanent tracer to that player, making everyone raidable, since they can freecam over 100k blocks and find the player (Version: 13.7.6-SNAPSHOT). The player shown is a "ghost player" thus not moving, but having the skin. The chunk is not loaded for the player, but when the crash the game, the player entity with the coords is printed to logs as well, thus the client knows the coords since it was send.

![image](https://user-images.githubusercontent.com/1629090/80600473-bd755980-8a2c-11ea-8f2c-de7748edd1d1.png)

How to replicate:
1. have a offline-mode server
2. have SkinsRestorer
3. use Aristios hacked client and enable tracers
4. login with 1 account with tracers active
5. login with another account
6. tracer will appear (on joining, if not login in multiple times)
7. freecam to the tracer, find the "ghost player" and note down coords

Edit:
Another way is to just use /skin set <any skin> with 1 player and the tracer ray still appears.

**Comment by Kongolan** [comment] 2020-04-29 13:27
I just see this is duplicated, well I still hope it gets fixed. My anarchy server is abusing this.

**Comment by xknat** [comment] 2020-05-01 13:59
Duplicate of #213

**Closed by xknat** 2020-05-01 13:59 UTC
