### ISSUE TITLE
Will Minecraft 1.19.3 be supported?

### ISSUE THREAD

**Issue by ghost** [SkinsRestorer/SkinsRestorerX#1145] opened 2022-12-12 10:39 UTC
Today I was using Paper Minecraft Server, and I updated my server file to 1.19.3, but it isn't supported...May you support it?

**Comment by AlexProgrammerDE** [comment] 2022-12-12 10:59
Duplicate of #1133

**Closed as not planned by AlexProgrammerDE** 2022-12-12 10:59 UTC
