### ISSUE TITLE
MineSkinAPI is overloaded, please try again later

### ISSUE THREAD

**Issue by pedrofracassi** [SkinsRestorer/SkinsRestorerX#477] opened 2021-04-13 12:24 UTC
## Describe the bug
When trying to change a skin through an URL, plugin fails and outputs an error to the console. Does not seem to be related to MineSkin, as the API is working fine.

## How can we reproduce what you got?
1. `/skin https://www.minecraftskins.com/uploads/skins/2021/04/13/fire-and-ice-herobrine-gaming-skin-17456487.png?v393`

**Expected behavior**
Plugin should change the player's skin

**Screenshots**
Plugin tells the player "MineSkin API is overloaded" and outputs an error to console
![image](https://user-images.githubusercontent.com/25179120/114551002-36b78d80-9c39-11eb-8a6d-848786228823.png)

## Server information

* SkinsRestorer: v14.0.2
* Spigot version: git-Paper-591, 1.16.5
* Java: 11
* plugin list bungee & spigot: AdvancedTeleport, AuthMe, CoreProtect, FastLogin, floodgate-bukkit, Geyser-Spigot, GriefPrevention, Harbor, LuckPerms, mcMMO, ProtocolLib, SkinsRestorer, TogglePvp*

### Error outputted when running /skin
```
[WARNING] .... net.skinsrestorer.shared.exception.SkinRequestException: [SkinsRestorer] Error: An error occurred while updating your skin. Please try again later!
[WARNING] .... at net.skinsrestorer.shared.utils.MineSkinAPI.genSkin(MineSkinAPI.java:62)
[WARNING] .... at net.skinsrestorer.bukkit.commands.SkinCommand.setSkin(SkinCommand.java:291)
[WARNING] .... at net.skinsrestorer.bukkit.commands.SkinCommand.setSkin(SkinCommand.java:218)
[WARNING] .... at net.skinsrestorer.bukkit.commands.SkinCommand.lambda$onSkinSetOther$2(SkinCommand.java:195)
[WARNING] .... at net.skinsrestorer.bukkit.commands.SkinCommand$$Lambda$6050.0000000096EFDC30.run(Unknown Source)
[WARNING] .... at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
[WARNING] .... at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
[WARNING] .... at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[WARNING] .... at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[WARNING] .... at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[WARNING] .... at java.base/java.lang.Thread.run(Unknown Source)
```

### Startup logs
https://gist.github.com/pedrofracassi/f3f85674df2de3b5012cc2b689ded53b

**Comment by xknat** [comment] 2021-04-13 12:40
How many players were on the server at the time of the error?
also are you using a lot of skin urls? like defaultskins url?

**Comment by pedrofracassi** [comment] 2021-04-14 20:55
> How many players were on the server at the time of the error?

I don't know exactly, but it seems to happen regardless of how many players are online and/or trying to use the command. It is a small private server that I play with friends in. Don't think it ever got over 12 players concurrently.

> also are you using a lot of skin urls? like defaultskins url?

My players usually grab skins from https://www.minecraftskins.com/ and use URLs to the skins from there.

---

I forgot to mention that using a username to set the skin instead of an URL seems to work just fine. I think it's cause then it doesn't need MineSkin to generate stuff?

**Comment by aljaxus** [comment] 2021-04-15 13:55
> I forgot to mention that using a username to set the skin instead of an URL seems to work just fine. I think it's cause then it doesn't need MineSkin to generate stuff?

Yes that is correct. MineSkin is used when there's a need to get a valid Mojang-signed skin file from an arbitrary image file.

**Comment by xknat** [comment] 2021-04-15 14:17
It seems to be that mineskin did add a spam checker when requesting the same skin over and over again.
Will need to see how this will need a rework

**Comment by pedrofracassi** [comment] 2021-04-15 20:14
It seems to happen even when requesting different skins from different URLs

**Comment by xknat** [comment] 2021-04-21 21:16
duplicate of https://github.com/SkinsRestorer/SkinsRestorerX/issues/434

**Closed by xknat** 2021-04-21 21:16 UTC
Labels: :clock10: awaiting information, :question: undecided
