### ISSUE TITLE
plugin does not working on velocity

### ISSUE THREAD

**Issue by Overwrite987** [SkinsRestorer/SkinsRestorerX#1030] opened 2022-08-06 10:23 UTC
## Describe the bug

The plugin does not work on latest velocity. At startup, it throws an error and does not perform its functions after starting the server. 

## How can we reproduce what you got?

1. Download latest velocity from **https://papermc.io/downloads#Velocity**
2. Download latest SR from https://www.spigotmc.org/resources/skinsrestorer.2124/
3. install the plugin on the proxy and restart it

## Server information

**velocity**

**Velocity 3.1.2-SNAPSHOT (git-8a63df2a-b168)**

* SkinsRestorer: 14.2.2
* Spigot version: 1.18.2 - purpur
* Bungeecord version: - 
* IF bungee, did you put the plugin on all servers: Yes
* Java: 17
* plugin list bungee & spigot: -
* MinecraftLauncher?: all
* if multiverse, (censored) worlds file: - 

## Logs

Replace the links below by a paste of your startup logs (if you run a **Bungeecord** server, please send startup logs
from **Bungeecord *AND* Spigot/Bukkit**)

**https://hastebin.app/62ee4065d5c6ab001c626c6f**

## Additional context

-

**Comment by xknat** [comment] 2022-08-06 10:39
duplicate of https://github.com/SkinsRestorer/SkinsRestorerX/issues/1026

**Closed by xknat** 2022-08-06 10:39 UTC
