### ISSUE TITLE
Vanish plugins incompatibility

### ISSUE THREAD

**Issue by Voiddar** [SkinsRestorer/SkinsRestorerX#235] opened 2020-04-27 17:15 UTC
## Describe the bug

Joining a server while vanished (with any vanish plugin) will show your name in tab until you disable and reenable vanish. Also happens when you change worlds.

## How can we reproduce what you got?
1. Install EssentialsX, VanishNoPacket or SuperVanish (tested with all these)
2. Config them to join vanished (VanishNoPacket has this by default)
3. Have an alt account with default permissions online
4. Join with the sever with the OP permissions account
5. Switch to the alt account and press TAB, you should be able to see the name of the OP account even if vanished.
NOTE: This also happens when changing worlds
1. The same
2. Not needed
3. Have both accounts online, OP account unvanished
4. use /vanish in the op account
5. use /world in the op account or any other command that lets you change worlds
6. Switch to alt account and press tab, OP account's name should appear too

**Expected behavior**
When a player joins vanished or changes worlds, their name doesn't appear in tab 

## Server information

PaperSpigot 1.14.4 243

**What version? Do NOT answer LATEST**
SkinsRestorer: 13.7.5 (release)
Java: 8

## Logs
There are no error messages in console or in-game chat

**Comment by xknat** [comment] 2020-04-27 17:22
Duplicate of #100

**Closed by xknat** 2020-04-27 17:22 UTC
