### ISSUE TITLE
Logger fails to load on bukkit 1.8.8

### ISSUE THREAD

**Issue by Danila767** [SkinsRestorer/SkinsRestorerX#1155] opened 2022-12-20 23:35 UTC
Tested SkinsRestorer 14.2.3, Java 11/18, FlamePaper 96608d0

```
[02:28:48 WARN]: java.lang.NullPointerException
[02:28:48 WARN]:        at net.skinsrestorer.shared.utils.log.SRLogger.load(SRLogger.java:49)
[02:28:48 WARN]:        at net.skinsrestorer.bukkit.SkinsRestorerBukkit.pluginStartup(SkinsRestorerBukkit.java:103)
[02:28:48 WARN]:        at net.skinsrestorer.bukkit.SkinsRestorerBootstrap.onEnable(SkinsRestorerBootstrap.java:31)
[02:28:48 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[02:28:48 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[02:28:48 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407)
[02:28:48 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:359)
[02:28:48 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:318)
[02:28:48 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:373)
[02:28:48 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:337)
[02:28:48 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:327)
[02:28:48 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:255)
[02:28:48 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
[02:28:48 WARN]:        at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by xknat** [comment] 2022-12-20 23:55
Java 18 is not tested / supported

**Comment by xknat** [comment] 2022-12-20 23:57
Got more information than just this error?
What kind of 1.8.8 are you using? Spigot / paper?
Any additional info like implement enhanced?
Mods forge?

**Comment by Danila767** [comment] 2022-12-21 14:44
> 

Fork Paper [link](https://github.com/2lstudios-mc/FlamePaper)

**Comment by Danila767** [comment] 2022-12-21 14:45
> Got more information than just this error? What kind of 1.8.8 are you using? Spigot / paper? Any additional info like implement enhanced? Mods forge?

No mods, There was no such warning in version 14.2.3

**Comment by Danila767** [comment] 2022-12-21 14:47
This warning occurs when starting the server and the plugin

**Comment by xknat** [comment] 2022-12-25 12:46
duplicate of https://github.com/SkinsRestorer/SkinsRestorerX/issues/1130
merged your log

**Closed as completed by xknat** 2022-12-25 12:46 UTC
