### ISSUE TITLE
Vanilla require resourcepack prompt gets skipped

### ISSUE THREAD

**Issue by vaporvee** [SkinsRestorer/SkinsRestorerX#818] opened 2022-01-15 16:50 UTC
## Describe the bug

When you force the player to use a server resourcepack(new vanilla feature since 1.17) the dialogue will be skipped when i have skinrestorer installed.

## How can we reproduce what you got?

1. Install SkinRestorer
2. Setup a server resourcepack in the server.properties
3. and also turn on require-resource-pack=true in the server.properties(idk if its also for the optional server resourcepack dialogue)
4. Join the server with "Server Resource Packs: Prompt"
5. Try the whole thing without installing SkinRestorer again

**Expected behavior**
Let me use the dialogue because otherwise the player has to use the server leave button the player can't play without the resourcepack

**Screenshots**
<img src="https://cdn.discordapp.com/attachments/825019604207927326/931950349252714567/unknown.png"><img>

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

**What version? Do NOT answer LATEST**

* SkinsRestorer: 14.1.10
* Paper version: git-Paper-152
* Java: openjdk 17.0.1
* plugin list: 
AdvancedBan, AFK-Kick, Antispam, AuthMe, AutoVillageProtect, BanItem, BetterEconomy, ChatLab, ClearLag, ComplexTurrets, ConsoleSpamFix, CustomCrafting, DeadChest, DisableEnderchest, DiscordSRV, DiscordSRVUtils, EconomyShopGUI, explock, FastLogin, GFly, GroupManager, ImageMaps, Instruments, InventoryRollbackPlus, InvSeePlusPlus, KillRewardsPlugin, LootChest, MattyPlays270Furniture, Mclogs, Multiverse-Core, NBTAPI, PlaceholderAPI, PlayerKits, PlugManX, ProtocolLib, QualityArmory, QualityArmoryVehicles2, SimpleClans, SimpleSpawn, SimpleTpa, SkinsRestorer, StartupCommands, SuperVanish, TabList, Themis, TrollBoss, Vault, Whitelist, WolfyUtilities, WorldEdit, WorldGuard

## Logs
https://mclo.gs/YBf0v35

**Comment by xknat** [comment] 2022-01-15 16:54
Duplicate of #582

**Closed as completed by xknat** 2022-01-15 16:54 UTC
