### ISSUE TITLE
/skin random

### ISSUE THREAD

**Issue by breezefps** [SkinsRestorer/SkinsRestorerX#1289] opened 2023-06-14 14:32 UTC
### Is there an existing feature request for this?

- [X] I have searched the existing feature requests

### Describe your feature request

A command for a totally random skin. Simple but very useful for new users that just want to find new skins :)

**Comment by xknat** [comment] 2023-06-14 14:33
Duplicate of https://github.com/SkinsRestorer/SkinsRestorerX/issues/265

**Closed as completed by xknat** 2023-06-14 14:33 UTC
