### ISSUE TITLE
Folia broke with last update

### ISSUE THREAD

**Issue by Listum** [SkinsRestorer/SkinsRestorerX#1709] opened 2024-07-22 10:47 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Plugin not work after latest update

### How can we reproduce what you got?

1. Update plugin (previous version works fine)
2. Isnt working anymore

### Server/Error Logs

https://bin.birdflop.com/miviluteji.makefile

### Minecraft implementation

```markdown
- Proxy: Velocity(No difference)
- Backend: Folia
```

### What client are you using?

PolyMC

### SkinsRestorer Version

15.3.0

### List of plugins

Plugins(8): Chunky, ChunkyBorder, CoreProtect, FreedomChat, GSit, SkinsRestorer, TAB, SimpleVoiceChat

### Java Version

GraalVM 21

### Does your issue require a plugin in order to reproduce?

No

**Comment by HalmenNime** [comment] 2024-07-22 10:55
Same problem, PaperMC 1.19.4, previous version plugin work normal

**Comment by AlexProgrammerDE** [comment] 2024-07-22 10:55
On it.

**Comment by AlexProgrammerDE** [comment] 2024-07-22 10:56
I've removed the jar from the release for now. I'll readd it once the bug is fixed.

**Comment by HalmenNime** [comment] 2024-07-22 10:59
> I've removed the jar from the release for now. I'll readd it once the bug is fixed.

Yea, good idea

**Comment by HalmenNime** [comment] 2024-07-22 11:01
Anyway, who want use skinrestorer at the moment without update, you can create file "noupdate.txt" in plugin directory

**Comment by AlexProgrammerDE** [comment] 2024-07-22 11:04
Not needed, the update is disabled since I removed the jar from the release.

**Comment by Listum** [comment] 2024-07-22 11:04
> Anyway, who want use skinrestorer at the moment without update, you can create file "noupdate.txt" in plugin directory

THANKS ALOT

**Comment by HalmenNime** [comment] 2024-07-22 11:05
> Anyway, who want use skinrestorer at the moment without update, you can create file "noupdate.txt" in plugin directory

As specified in the plugin config

![image](https://github.com/user-attachments/assets/fac614d0-a1a4-426f-89de-4f75f92c8e77)

**Comment by Listum** [comment] 2024-07-22 11:05
> Not needed, the update is disabled since I removed the jar from the release.

https://bin.birdflop.com/rakupokame.swift

**Comment by AlexProgrammerDE** [comment] 2024-07-22 11:07
Well that error is displayed because you enabled debug mode. It should be harmless.

**Comment by AlexProgrammerDE** [comment] 2024-07-22 11:08
![image](https://github.com/user-attachments/assets/159022b1-3298-4ebb-9a92-9ec5e0c99402)
Was able to reproduce

**Comment by AlexProgrammerDE** [comment] 2024-07-22 11:10
Fix will be released shortly

**Closed as completed** 2024-07-22 11:10 UTC

**Comment by AlexProgrammerDE** [comment] 2024-07-22 11:13
Fix was released: https://github.com/SkinsRestorer/SkinsRestorer/releases/tag/15.3.0
