### ISSUE TITLE
MYSQL connection problem

### ISSUE THREAD

**Issue by Link0Darck** [SkinsRestorer/SkinsRestorerX#693] opened 2021-09-21 18:15 UTC
Hello,
I'm using MySQL 5.7.11 so here's the error (otherwise the plugin still works but spams this error)
https://pastebin.com/qaZZwEPE

**Comment by xknat** [comment] 2021-09-21 18:26
@Link0Darck pls provide /sr status

**Comment by Link0Darck** [comment] 2021-09-22 21:27
> /sr status

here is the information sorry for the delay and I use water all last version

`[22sept.2021 23:24:14.768] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] ----------------------------------------------
[22sept.2021 23:24:14.769] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Checking needed services for SR to work properly...
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Working UUID API count:  3
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Working Profile API count: 3
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] The plugin currently is in a working state.
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] ----------------------------------------------
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] SkinsRestorer v14.1.5
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Server: git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449
[22sept.2021 23:24:15.797] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] BungeeMode: Bungee-Plugin
[22sept.2021 23:24:15.797] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Finished checking services.
[22sept.2021 23:24:15.797] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] ----------------------------------------------`

**Comment by xknat** [comment] 2021-09-22 21:31
maybe @AlexProgrammerDE knows

**Comment by Link0Darck** [comment] 2021-09-22 21:33
> maybe @AlexProgrammerDE knows

the worst is that skinrestorer works after it says connect but it spams me this error lol :D

**Comment by aljaxus** [comment] 2021-09-23 12:07
@Link0Darck next time please format the error into a more readable state;
```
[22sept.2021 23:24:14.768] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] ----------------------------------------------
[22sept.2021 23:24:14.769] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Checking needed services for SR to work properly...
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Working UUID API count: 3
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Working Profile API count: 3
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] The plugin currently is in a working state.
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] ----------------------------------------------
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] SkinsRestorer v14.1.5
[22sept.2021 23:24:15.796] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Server: git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:306121c:449
[22sept.2021 23:24:15.797] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] BungeeMode: Bungee-Plugin
[22sept.2021 23:24:15.797] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] Finished checking services.
[22sept.2021 23:24:15.797] [Render thread/INFO] [net.minecraft.client.gui.NewChatGui/]: [CHAT] ----------------------------------------------
```

**Comment by aljaxus** [comment] 2021-09-23 12:13
ref;
* https://stackoverflow.com/a/18823705/11276254
* metabase/metabase#9885

We are also using the [MariaDB jdbc driver](https://github.com/SkinsRestorer/SkinsRestorerX/blob/878e18d159646f545adaacf662b05a21f296d8cf/src/main/java/net/skinsrestorer/shared/storage/MySQL.java#L62) which may not be compatible with old MySQL versions. Which version of which database are you using? (eg. MySQL, MariaDB)

**Comment by Link0Darck** [comment] 2021-09-23 14:15
> ref;
> 
> * https://stackoverflow.com/a/18823705/11276254
> * [Metabase 0.32.5 - unexpected end of stream, read 0 bytes from 7 metabase/metabase#9885](https://github.com/metabase/metabase/issues/9885)
> 
> We are also using the [MariaDB jdbc driver](https://github.com/SkinsRestorer/SkinsRestorerX/blob/878e18d159646f545adaacf662b05a21f296d8cf/src/main/java/net/skinsrestorer/shared/storage/MySQL.java#L62) which may not be compatible with old MySQL versions. Which version of which database are you using? (eg. MySQL, MariaDB)

Hello,
I'm using MySQL 5.7.11 I marked it above

**Comment by aljaxus** [comment] 2021-09-23 14:48
Yeah sorry, missed it :<

Can you try spinning up an MariaDB instance (just a test via docker, so you can simply discard it afterwards), try to connect to it and see if the issue persists?

**Comment by Link0Darck** [comment] 2021-09-23 18:55
> Yeah sorry, missed it :<
> 
> Can you try spinning up an MariaDB instance (just a test via docker, so you can simply discard it afterwards), try to connect to it and see if the issue persists?

Sorry, I didn't quite understand what you wanted to do (I'm French)

**Comment by aljaxus** [comment] 2021-09-23 18:57
Try connecting SkinsRestorer to MariaDB because your MySQL installation is very, very old. ([release notes for MySQL 5.7.11](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-11.html))

**Comment by Link0Darck** [comment] 2021-09-25 14:12
> Try connecting SkinsRestorer to MariaDB because your MySQL installation is very, very old. ([release notes for MySQL 5.7.11](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-11.html))

Sorry but I can't change the version or even switch to marian DB I use this database because I need it and the old version of your plugin i had no problem even the plugin works but it spam is error in the consol

**Comment by aljaxus** [comment] 2021-09-25 14:18
> 
> 
> > Try connecting SkinsRestorer to MariaDB because your MySQL installation is very, very old. ([release notes for MySQL 5.7.11](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-11.html))
> 
> Sorry but I can't change the version or even switch to marian DB I use this database because I need it and the old version of your plugin i had no problem even the plugin works but it spam is error in the consol

Yes - new version does not work because we are now using a newer database driver. Your MySQL version is **five and a half years old**. Since you are using shared hosting, ask your provider to update the database.

What we could do on the other hand is add the option to customize the database driver in [`config.yml`](https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/src/main/resources/config.yml#L103) - @AlexProgrammerDE ?

**Comment by Link0Darck** [comment] 2021-09-25 14:22
> > > Essayez de connecter SkinsRestorer à MariaDB car votre installation MySQL est très, très ancienne. ( [notes de version pour MySQL 5.7.11](https://dev.mysql.com/doc/relnotes/mysql/5.7/en/news-5-7-11.html) )
> > 
> > 
> > Désolé mais je ne peux pas changer la version ou même passer à marian DB J'utilise cette base de données car j'en ai besoin et l'ancienne version de votre plugin je n'ai eu aucun problème même le plugin fonctionne mais c'est du spam c'est une erreur dans la consol
> 
> Oui - la nouvelle version ne fonctionne pas car nous utilisons maintenant un pilote de base de données plus récent. Votre version de MySQL a **cinq ans et demi** . Puisque vous utilisez un hébergement mutualisé, demandez à votre fournisseur de mettre à jour la base de données.
> 
> Ce que nous pourrions faire d'autre part, c'est ajouter l'option pour personnaliser le pilote de base de données dans [`config.yml`](https://github.com/SkinsRestorer/SkinsRestorerX/blob/dev/src/main/resources/config.yml#L103)- @AlexProgrammerDE ?

Hello,
I have my own server at home but I will not update MYSQL because I need the version or I am for something else that needs this specific version
thank you in advance

**Comment by aljaxus** [comment] 2021-09-25 18:45
Well if you have your own server you can just install Docker and spin up a single instance of MariaDB just for SkinsRestorer (and any other updated software that you might be running)

**Comment by Link0Darck** [comment] 2021-10-03 17:30
> Well if you have your own server you can just install Docker and spin up a single instance of MariaDB just for SkinsRestorer (and any other updated software that you might be running)

I see but I don't know this method yet and then if the last version causes me a lot of problems to switch to the second last one

**Comment by AlexProgrammerDE** [comment] 2021-10-03 17:39
@Link0Darck 
> MariaDB Connector/J is compatible with all MariaDB and MySQL server versions 5.5.3 and later.

Please ensure you are using a recent version of mysql to work with the newest version of SkinsRestorer. I see from messages above you are running `5.7.11`, but I am unsure whether this is a mariadb driver issue or something different. After a bit of googling it seems like the issue could be the wait timeout, which may be caused by an instable connection to the DB and closing the connection with SR. You can read more about it here: 
[Stackoverflow comment 1](https://stackoverflow.com/a/33307702/12871087)
[Stackoverflow comment 2](https://stackoverflow.com/a/52052368/12871087)
[mysql info](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_wait_timeout)

Increasing the wait timeout as explained in the Stackoverflow comment 2 should hopefully fix your issue.

**Comment by Link0Darck** [comment] 2021-10-03 17:42
> @Link0Darck
> 
> > MariaDB Connector/J is compatible with all MariaDB and MySQL server versions 5.5.3 and later.
> 
> Please ensure you are using a recent version of mysql to work with the newest version of SkinsRestorer. I see from messages above you are running `5.7.11`, but I am unsure whether this is a mariadb driver issue or something different. After a bit of googling it seems like the issue could be the wait timeout, which may be caused by an instable connection to the DB and closing the connection with SR. You can read more about it here: [Stackoverflow comment 1](https://stackoverflow.com/a/33307702/12871087) [Stackoverflow comment 2](https://stackoverflow.com/a/52052368/12871087) [mysql info](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_wait_timeout)
> 
> Increasing the wait timeout as explained in the Stackoverflow comment 2 should hopefully fix your issue.

I'm not sure how long it takes to connect, because otherwise I don't have a problem with the skinrestorer mentioned above.

**Comment by Link0Darck** [comment] 2021-10-04 17:52
> @Link0Darck
> 
> > MariaDB Connector/J is compatible with all MariaDB and MySQL server versions 5.5.3 and later.
> 
> Please ensure you are using a recent version of mysql to work with the newest version of SkinsRestorer. I see from messages above you are running `5.7.11`, but I am unsure whether this is a mariadb driver issue or something different. After a bit of googling it seems like the issue could be the wait timeout, which may be caused by an instable connection to the DB and closing the connection with SR. You can read more about it here: [Stackoverflow comment 1](https://stackoverflow.com/a/33307702/12871087) [Stackoverflow comment 2](https://stackoverflow.com/a/52052368/12871087) [mysql info](https://dev.mysql.com/doc/refman/5.6/en/server-system-variables.html#sysvar_wait_timeout)
> 
> Increasing the wait timeout as explained in the Stackoverflow comment 2 should hopefully fix your issue.

how to fix the problem since the mysql server is local

**Comment by xknat** [comment] 2022-06-30 18:33
@Link0Darck resolved on latest dev build?

**Comment by Link0Darck** [comment] 2022-07-01 01:39
> @Link0Darck resolved on latest dev build?

Yes me problem is dix thx you good support 😺

**Closed as completed** 2022-07-01 08:48 UTC
