### ISSUE TITLE
Malformed input or input contains unmappable characters

### ISSUE THREAD

**Issue by notikj** [SkinsRestorer/SkinsRestorerX#1196] opened 2023-02-10 19:59 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

If you enter incorrect characters in /skin set, it will give an error and not let you on the server.
At least with bungee it is.

https://pastes.dev/Q2WqpptF95

### How can we reproduce what you got?

for example, you need to write the command /skin set ·уоу· (copy), and re-upload to the server.

### Minecraft implementation

```markdown
- Proxy: GuardHexa last version
```

### What client are you using?

TLauncher

### SkinsRestorer Version

14.2.5

### List of plugins

bungee

### Java Version

Temurin-17.0.5+8 (build 17.0.5+8)

### Does your issue require a plugin in order to reproduce?

No

**Comment by xknat** [comment] 2023-02-14 19:46
duplicate of https://github.com/SkinsRestorer/SkinsRestorerX/issues/1194

**Closed as completed by xknat** 2023-02-14 19:46 UTC
