### ISSUE TITLE
Trojan:Script/Wacatac.H!ml Detection from Windows Defender

### ISSUE THREAD

**Issue by Turjoy9** [SkinsRestorer/SkinsRestorerX#1605] opened 2024-05-12 07:39 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

When starting the server the plugin (downloaded from github's release page) was detected as a trojan, more specifically as a `Trojan:Script/Wacatac.H!ml`

After downloading the plugin and running the server first time, it didn't detect anything but on the 2nd time it was detected by the AV and the server itself (more in the provided log). No modification to the jar was made and the 2nd run was done shortly after the first one.

![image](https://github.com/SkinsRestorer/SkinsRestorer/assets/60349233/6f35cc46-87ab-4985-be1d-7a654c42f91d)
![image](https://github.com/SkinsRestorer/SkinsRestorer/assets/60349233/4e8fea0e-63d2-4391-a841-5fb68db8fd1e)

After that, redownloaded the jar from release and did a quick scan at virustotal and gave this result [https://www.virustotal.com/gui/file/f25462c687abbc716f95243682731ead05ebdb12b7fdb636873a9097aaa568ca/details](url)

### Server/Error Logs

https://bin.birdflop.com/zemuzusilo

### Minecraft implementation

```markdown
- Proxy: none
- Backend: PaperMC 1.17.1 version git-Paper-411
```

### SkinsRestorer Version

15.0.13

### List of plugins

Plugins (13): ChestSort, CleanPing, CommandWhitelist, GSit, Hat, InvisibleItemFrame, LuckPerms, MiniMOTD, OpenInv, ProtocolLib, spark, ViaBackwards, ViaVersion

### Java Version

Java 17 (OpenJDK 64-Bit Server VM 17.0.11+9)

### Does your issue require a plugin in order to reproduce?

None

**Comment by AlexProgrammerDE** [comment] 2024-07-22 15:18
Duplicate of #1618

**Closed as not planned by AlexProgrammerDE** 2024-07-22 15:18 UTC
