### ISSUE TITLE
Skins Not Loading for Bedrock

### ISSUE THREAD

**Issue by KnightMikaza** [SkinsRestorer/SkinsRestorerX#1195] opened 2023-02-09 18:48 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

Bedrock recently updated to 1.19.60, meaning we had to update Geyser to its latest version, and sense then bedrock players can no longer see their skins, they just see Steve or Alex. If they type in the command to change their skin the screen freezes for a second and they get a notification that their skin changed/updated but they’re still Steve. Java doesn’t seem to have any issues, but I’m not sure. I tried to update skinrestorer and restarted the server: the issue still hasn’t fixed itself. 

### How can we reproduce what you got?

Play on bedrock 1.19.60 with geysers latest updated version: I guess?

### Minecraft implementation

```markdown
- Proxy: 
- Backend: This Server is running Craftbukkit version 3597-Spigot-4aa5ead-aaf4844f (MC:1.19.2) (Implementing API version 1.19.2-R0.1-Snapshot)
```

### What client are you using?

MCPE Launcher

### SkinsRestorer Version

14.2.8

### List of plugins

WorldEdit, Viaversion, floodgate, Coreprotect, skinrestorer, Geyser-spigot, GeyserUpdater

### Java Version

I don’t understand

### Does your issue require a plugin in order to reproduce?

No

**Comment by tinkeringmatt** [comment] 2023-04-28 05:06
Im having this same issue on bedrock on ps4 and mobile

Also using geyser but on bedrock 1.19.88
Using skin restorer 14.2.10

**Comment by xknat** [comment] 2023-07-05 12:24
duplicate of https://github.com/SkinsRestorer/SkinsRestorerX/issues/898

**Closed as completed by xknat** 2023-07-05 12:24 UTC
