### ISSUE TITLE
[BUG] SkinWithoutPerm & /skins & /skin set. [Paper 1.18.2]

### ISSUE THREAD

**Issue by BboyZeroOne** [SkinsRestorer/SkinsRestorerX#964] opened 2022-06-13 01:38 UTC
**SkinRestorerX: Latest version**
_Server: 1.18.2 (Paper 216)_

**Issues:** 
After disabling `SkinWithoutPerm: false` on bungee config, this is what I found:
1. Players with `skinsrestorer.command` and `skinsrestorer.command.set` could not use the command `/skin set (skin)`
2. Staff/Admins with OP or the permission `*` does not have access to use the command either, with a return message 'You do not have permission to execute this command!'
3. Changing `SkinWithoutPerm:` to true then executing `/sr reload` applies changes, but changing `SkinWithoutPerm:` to false then executing `/sr reload` does not.

**Besides that:**
1. `/skins` is bugged. Players who opens the `/skins` GUI could obtain player head instead of switching to the player skin.
2. While the GUI is bugged, players can obtain infinite player head + glass panes.

**Suggestions:**
1. Add a config where admins can modify the `/skins` GUI interface/materials.
2. Add an option to disable saving player's skin on join under "SkinRestorer/Skins" Folder. OR;
3. Add an option to disable player's skin to be shown on '/skins' GUI player skin list.

**Comment by xknat** [comment] 2022-06-13 08:02
not a bug, user mistake.
Commands are run from bungee side, permissions should be given on the same place (bungee)

**Comment by xknat** [comment] 2022-06-13 08:03
> /skins is bugged. Players who opens the /skins GUI could obtain player head instead of switching to the player skin.

Already resolved. Good thing your not using our dev build so this can be closed. already resolved in dev build

**Closed as completed by xknat** 2022-06-13 08:03 UTC

**Comment by BboyZeroOne** [comment] 2022-06-13 11:13
Sorry, I forgot to add one more:
After denying permissions on worldguard `blocked-cmds` list, users still can use the command.

**Comment by xknat** [comment] 2022-06-13 11:26
> Sorry, I forgot to add one more: After denying permissions on worldguard `blocked-cmds` list, users still can use the command.

Thanks, but also not a bug.
