### ISSUE TITLE
error to console

### ISSUE THREAD

**Issue by 1Pootis1** [SkinsRestorer/SkinsRestorerX#1023] opened 2022-08-04 00:12 UTC
## Describe the bug

**Screenshots**
![image](https://user-images.githubusercontent.com/73141732/182736122-167a87f9-61b3-491f-b517-849d1c4495df.png)

## Server information

**On what platform does your server run? (Bungeecord/Spigot/Bukkit)**

Paper 1.19.1 build 109

**What version? Do NOT answer LATEST**

* SkinsRestorer: 14.2.1
* Spigot version: 1.19.1
* Bungeecord version: -
* IF bungee, did you put the plugin on all servers: Yes / No
* Java: 17
* plugin list bungee & spigot:  BetterSleeping4, Chatty, DecentHolograms, DeluxeMenus, Essentials, EssentialsProtect, EssentialsSpawn, LuckPerms, PlaceholderAPI, ProtocolLib, SkinsRestorer, TAB, Vault, ViaBackwards, ViaVersion, WorldBorder, WorldEdit, WorldGuard, WorldsColor  
* MinecraftLauncher?:
* if multiverse, (censored) worlds file:

## Logs

https://hastebin.app/62eb0efdd5c6ab001c626c50

**Comment by xknat** [comment] 2022-08-04 08:55
Duplicate of https://github.com/SkinsRestorer/SkinsRestorerX/issues/1014

**Closed as completed by xknat** 2022-08-04 08:55 UTC
