### ISSUE TITLE
1.19.1 Support. Console starting Error full log

### ISSUE THREAD

**Issue by Futodama** [SkinsRestorer/SkinsRestorerX#1019] opened 2022-08-02 09:18 UTC
[12:13:40] [Server thread/INFO]: [SkinsRestorer] Enabling SkinsRestorer v14.2.1
[12:13:40] [Server thread/ERROR]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39mYour Minecraft version is not supported by this version of SkinsRestorer! Is there a newer version available? If not, join our discord server![0;39m
[12:13:40] [Server thread/WARN]: net.skinsrestorer.shared.exception.InitializeException: net.skinsrestorer.shared.exception.InitializeException: No mapping for this minecraft version found!
[12:13:40] [Server thread/WARN]: 	at SkinsRestorer.jar//net.skinsrestorer.bukkit.skinrefresher.PaperSkinRefresher.<init>(PaperSkinRefresher.java:92)
[12:13:40] [Server thread/WARN]: 	at SkinsRestorer.jar//net.skinsrestorer.bukkit.SkinApplierBukkit.detectRefresh(SkinApplierBukkit.java:78)
[12:13:40] [Server thread/WARN]: 	at SkinsRestorer.jar//net.skinsrestorer.bukkit.SkinApplierBukkit.<init>(SkinApplierBukkit.java:62)
[12:13:40] [Server thread/WARN]: 	at SkinsRestorer.jar//net.skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:139)
[12:13:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[12:13:40] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370)
[12:13:40] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542)
[12:13:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563)
[12:13:40] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477)
[12:13:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636)
[12:13:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422)
[12:13:40] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:306)
[12:13:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1124)
[12:13:40] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305)
[12:13:40] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[12:13:40] [Server thread/WARN]: Caused by: net.skinsrestorer.shared.exception.InitializeException: No mapping for this minecraft version found!
[12:13:40] [Server thread/WARN]: 	at SkinsRestorer.jar//net.skinsrestorer.bukkit.skinrefresher.PaperSkinRefresher.<init>(PaperSkinRefresher.java:75)
[12:13:40] [Server thread/WARN]: 	... 14 more
[12:13:40] [Server thread/ERROR]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39mPaperSkinRefresher failed! (Are you using hybrid software?) Only limited support can be provided. Falling back to SpigotSkinRefresher.[0;39m
[12:13:40] [Server thread/ERROR]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39mYour Minecraft version is not supported by this version of SkinsRestorer! Is there a newer version available? If not, join our discord server![0;39m
[12:13:40] [Server thread/ERROR]: [33;1m[[32;22mSkinsRestorer[33;1m] [0;39m[31;1m[4mCould not initialize SkinApplier! Please report this on our discord server! [0;39m
net.skinsrestorer.shared.exception.InitializeException: No mapping for this minecraft version found! (4cc0cc97cac491651bff3af8b124a214)
	at net.skinsrestorer.bukkit.skinrefresher.MappingSpigotSkinRefresher.<init>(MappingSpigotSkinRefresher.java:45) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.SkinApplierBukkit.selectSpigotRefresher(SkinApplierBukkit.java:90) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.SkinApplierBukkit.detectRefresh(SkinApplierBukkit.java:85) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.SkinApplierBukkit.<init>(SkinApplierBukkit.java:62) ~[SkinsRestorer.jar:?]
	at net.skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:139) ~[SkinsRestorer.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.1.jar:git-Paper-101]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:13:40] [Server thread/ERROR]: Error occurred while enabling SkinsRestorer v14.2.1 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "net.skinsrestorer.bukkit.SkinApplierBukkit.getRefresh()" because "this.skinApplierBukkit" is null
	at net.skinsrestorer.bukkit.SkinsRestorer.onEnable(SkinsRestorer.java:144) ~[SkinsRestorer.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-101]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.19.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:422) ~[paper-1.19.1.jar:git-Paper-101]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:306) ~[paper-1.19.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-101]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-101]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[12:13:40] [Server thread/INFO]: [SkinsRestorer] Disabling SkinsRestorer v14.2.1

**Comment by xknat** [comment] 2022-08-02 11:39
User problem

**Comment by xknat** [comment] 2022-08-02 11:40
Also duplicate of https://github.com/SkinsRestorer/SkinsRestorerX/issues/1014

**Closed as completed by xknat** 2022-08-02 11:39 UTC
