### ISSUE TITLE
Bungeecord Skinrestorer error on enable

### ISSUE THREAD

**Issue by JunkieCraft** [SkinsRestorer/SkinsRestorerX#968] opened 2022-06-14 17:52 UTC
I am having problems when I try to start skinrestorer in bungeecoord.

I have the latest version of skinrestorer 14.1.15 installed on each paperSpigot server and on my bungeecord server.

When I start the bungee server I get the following error:

`14.06 17:47:30 [Server] WARNING Error loading plugin SkinsRestorer
14.06 17:47:30 [Server] INFO java.lang.reflect.InvocationTargetException
14.06 17:47:30 [Server] INFO at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
14.06 17:47:30 [Server] INFO at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:78)
14.06 17:47:30 [Server] INFO at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
14.06 17:47:30 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
14.06 17:47:30 [Server] INFO at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
14.06 17:47:30 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:341)
14.06 17:47:30 [Server] INFO at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:250)
14.06 17:47:30 [Server] INFO at net.md_5.bungee.BungeeCord.start(BungeeCord.java:271)
14.06 17:47:30 [Server] INFO at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:67)
14.06 17:47:30 [Server] INFO at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
14.06 17:47:30 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/md_5/bungee/connection/LoginResult$Property
14.06 17:47:30 [Server] INFO at java.base/java.lang.ClassLoader.defineClass1(Native Method)
14.06 17:47:30 [Server] INFO at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1010)
14.06 17:47:30 [Server] INFO at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
14.06 17:47:30 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.findClass(PluginClassloader.java:152)
14.06 17:47:30 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:586)
14.06 17:47:30 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:66)
14.06 17:47:30 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
14.06 17:47:30 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
14.06 17:47:30 [Server] INFO at net.skinsrestorer.api.property.PropertyRegistry.selectPropertyForPlatform(PropertyRegistry.java:29)
14.06 17:47:30 [Server] INFO at net.skinsrestorer.shared.utils.connections.MojangAPI.<init>(MojangAPI.java:67)
14.06 17:47:30 [Server] INFO at net.skinsrestorer.bungee.SkinsRestorer.<init>(SkinsRestorer.java:72)
14.06 17:47:30 [Server] INFO ... 10 more
14.06 17:47:30 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.md_5.bungee.connection.LoginResult$Property
14.06 17:47:30 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:103)
14.06 17:47:30 [Server] INFO at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:59)
14.06 17:47:30 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
14.06 17:47:30 [Server] INFO ... 21 more`

bungee version: build 1644
paperSpigot version: 1.18.2 build 379

On the PaperSpigot servers no configuration file is generated, and on Bungee no folder is generated because SkinRestorer fails to start.

**Comment by MrPepsikk** [comment] 2022-06-15 14:37
I have a same error on BungeeCord server but I'm using version 1.19 of BungeeCord so It's quite annoying ngl =D

**Comment by AlexProgrammerDE** [comment] 2022-06-15 14:41
Duplicate of #956

**Closed as completed by AlexProgrammerDE** 2022-06-15 14:41 UTC
