### ISSUE TITLE
When I change skin via command or from the GUI, for the change to take place I have to exit and re-enter the server

### ISSUE THREAD

**Issue by NERFER-4** [SkinsRestorer/SkinsRestorerX#1224] opened 2023-03-14 18:05 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Are you using forge?

No

### Installed conforming to our guide?

- [X] I have read the installation guide and performed all steps

### Describe your issue

When I use the command /skins to change my skin from the GUI or when I use the command /skin (skin-name), my skin doesn't change. To see that it has changed I need to exit and back into the server. But if someone else in the server changes skin I see that his skin has changed without leaving and re-entering the server. This occurs for all players playing on the server, how can I fix it?

### How can we reproduce what you got?

1. Enter the server
2. Type /skins command and select the skin you want to choose
3. See that your skin doesn't changed
4. Exit the server and join again
5. See that now your skin has changed

### Minecraft implementation

```markdown
- Backend: This server is running Paper version git-Paper-448 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 155aa36)
```

### What client are you using?

TLauncher

### SkinsRestorer Version

14.2.8

### List of plugins

CoreProtect, Essentials, EssentialsDiscord, floodgate, Geyser-Spigot, InvSeePlusPlus, InvSeePlusPlus_Clear, InvSeePlusPlus_Give, JukeBox, NoteBlockAPI, SkinsRestorer

### Java Version

java version "17.0.2" 2022-01-18 LTS

### Does your issue require a plugin in order to reproduce?

None

**Comment by NERFER-4** [comment] 2023-03-22 22:59
Please, could someone answer?

**Comment by xknat** [comment] 2023-03-22 23:00
Github is our issue tracker, we use it for confirmed bugs / enhancements.
We only give support on our discord so unless your issue is not a bug and you need support, please close it and ask in our discord

**Comment by xknat** [comment] 2023-03-22 23:01
looks like a paper 1.19.4 issue btw

**Comment by xknat** [comment] 2023-03-22 23:01
we will be looking for a fix.

**Comment by NERFER-4** [comment] 2023-03-23 22:09
I had this problem also with version 1.19.3.

**Comment by envizar** [comment] 2023-03-26 14:58
I found paper build that breaks SkinsRestorer
It's build 444 (Paper version git-Paper-444 (MC: 1.19.3)

**Comment by xknat** [comment] 2023-07-05 12:25
> I found paper build that breaks SkinsRestorer It's build 444 (Paper version git-Paper-444 (MC: 1.19.3)

Should be resolved now with our dev build.
can you test?

**Comment by AlexProgrammerDE** [comment] 2024-07-23 14:13
stale

**Closed as not planned by AlexProgrammerDE** 2024-07-23 14:13 UTC
